name: CI Windows

on:
  push:
    paths-ignore:
      - '**.md'
      - '.github/workflows/ci_linux.yml'
      - '.github/workflows/ci_macos.yml'
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x86, x64]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.platform }}-${{ matrix.configuration }}'
